name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Development Dependencies
        run: pip install pytest pytest-html

      - name: Display directory structure
        run: ls -R

      - name: Run tests and generate reports
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: pytest --junitxml=pytest_report.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: pytest_report.xml
